I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 15, in script
    define lista = [inicio_Carreira, status,decision_uni]
  File "game/script.rpy", line 15, in script
    define lista = [inicio_Carreira, status,decision_uni]
  File "game/script.rpy", line 15, in <module>
    define lista = [inicio_Carreira, status,decision_uni]
NameError: name 'inicio_Carreira' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 560, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 15, in script
    define lista = [inicio_Carreira, status,decision_uni]
  File "game/script.rpy", line 15, in script
    define lista = [inicio_Carreira, status,decision_uni]
  File "renpy/ast.py", line 2213, in execute
    self.set()
  File "renpy/ast.py", line 2224, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 15, in <module>
    define lista = [inicio_Carreira, status,decision_uni]
NameError: name 'inicio_Carreira' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
ProjetoGame 1.0
Sat May 28 13:46:17 2022
